targets:
  - name: gobot
    sources:
      - /pkg/lib/translate/ja.yaml
    file: /pkg/lib/translate/lang/%two_letters_code%.yaml
    format: xliff
files:
  - source: /pkg/lib/translate/ja.yaml
    translation: /pkg/lib/translate/lang/%two_letters_code%.yaml
