services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/sabafly/gobot:latest
    tty: true
    env_file:
      - ./mysql/.env
      - ./.env
    volumes:
      - type: bind
        source: ./lang
        target: /app/lang
      - type: bind
        source: ./locales
        target: /app/locales
      - type: bind
        source: ./.config
        target: /app/.config
      - type: bind
        source: ./gobot.yml
        target: /app/gobot.yml
    ports:
      - "6060:6060" # Pprof port
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    env_file:
      - ./mysql/.env
    volumes:
      - type: volume
        source: gobot_volume
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
    restart: unless-stopped
  sql-gui:
    image: phpmyadmin/phpmyadmin:latest
    restart: no
    ports:
      - "8123:80"
    env_file:
      - ./mysql/.env
    environment:
      - PMA_HOST=mysql

volumes:
  gobot_volume:
    driver: local

networks:
  default:
    driver: bridge
