// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	snowflake "github.com/disgoorg/snowflake/v2"
	"github.com/sabafly/gobot/ent/guild"
	"github.com/sabafly/gobot/ent/member"
	"github.com/sabafly/gobot/ent/user"
	"github.com/sabafly/gobot/internal/permissions"
	"github.com/sabafly/gobot/internal/xppoint"
)

// MemberCreate is the builder for creating a Member entity.
type MemberCreate struct {
	config
	mutation *MemberMutation
	hooks    []Hook
}

// SetPermission sets the "permission" field.
func (_c *MemberCreate) SetPermission(v permissions.Permission) *MemberCreate {
	_c.mutation.SetPermission(v)
	return _c
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_c *MemberCreate) SetNillablePermission(v *permissions.Permission) *MemberCreate {
	if v != nil {
		_c.SetPermission(*v)
	}
	return _c
}

// SetXp sets the "xp" field.
func (_c *MemberCreate) SetXp(v xppoint.XP) *MemberCreate {
	_c.mutation.SetXp(v)
	return _c
}

// SetNillableXp sets the "xp" field if the given value is not nil.
func (_c *MemberCreate) SetNillableXp(v *xppoint.XP) *MemberCreate {
	if v != nil {
		_c.SetXp(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *MemberCreate) SetUserID(v snowflake.ID) *MemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetLastXp sets the "last_xp" field.
func (_c *MemberCreate) SetLastXp(v time.Time) *MemberCreate {
	_c.mutation.SetLastXp(v)
	return _c
}

// SetNillableLastXp sets the "last_xp" field if the given value is not nil.
func (_c *MemberCreate) SetNillableLastXp(v *time.Time) *MemberCreate {
	if v != nil {
		_c.SetLastXp(*v)
	}
	return _c
}

// SetMessageCount sets the "message_count" field.
func (_c *MemberCreate) SetMessageCount(v uint64) *MemberCreate {
	_c.mutation.SetMessageCount(v)
	return _c
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_c *MemberCreate) SetNillableMessageCount(v *uint64) *MemberCreate {
	if v != nil {
		_c.SetMessageCount(*v)
	}
	return _c
}

// SetLastNotifiedLevel sets the "last_notified_level" field.
func (_c *MemberCreate) SetLastNotifiedLevel(v uint64) *MemberCreate {
	_c.mutation.SetLastNotifiedLevel(v)
	return _c
}

// SetNillableLastNotifiedLevel sets the "last_notified_level" field if the given value is not nil.
func (_c *MemberCreate) SetNillableLastNotifiedLevel(v *uint64) *MemberCreate {
	if v != nil {
		_c.SetLastNotifiedLevel(*v)
	}
	return _c
}

// SetLastMessageHashes sets the "last_message_hashes" field.
func (_c *MemberCreate) SetLastMessageHashes(v []string) *MemberCreate {
	_c.mutation.SetLastMessageHashes(v)
	return _c
}

// SetGuildID sets the "guild" edge to the Guild entity by ID.
func (_c *MemberCreate) SetGuildID(id snowflake.ID) *MemberCreate {
	_c.mutation.SetGuildID(id)
	return _c
}

// SetGuild sets the "guild" edge to the Guild entity.
func (_c *MemberCreate) SetGuild(v *Guild) *MemberCreate {
	return _c.SetGuildID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *MemberCreate) SetUser(v *User) *MemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the MemberMutation object of the builder.
func (_c *MemberCreate) Mutation() *MemberMutation {
	return _c.mutation
}

// Save creates the Member in the database.
func (_c *MemberCreate) Save(ctx context.Context) (*Member, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberCreate) SaveX(ctx context.Context) *Member {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberCreate) defaults() {
	if _, ok := _c.mutation.Permission(); !ok {
		v := member.DefaultPermission
		_c.mutation.SetPermission(v)
	}
	if _, ok := _c.mutation.Xp(); !ok {
		v := member.DefaultXp
		_c.mutation.SetXp(v)
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		v := member.DefaultMessageCount
		_c.mutation.SetMessageCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberCreate) check() error {
	if _, ok := _c.mutation.Xp(); !ok {
		return &ValidationError{Name: "xp", err: errors.New(`ent: missing required field "Member.xp"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Member.user_id"`)}
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		return &ValidationError{Name: "message_count", err: errors.New(`ent: missing required field "Member.message_count"`)}
	}
	if len(_c.mutation.GuildIDs()) == 0 {
		return &ValidationError{Name: "guild", err: errors.New(`ent: missing required edge "Member.guild"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Member.user"`)}
	}
	return nil
}

func (_c *MemberCreate) sqlSave(ctx context.Context) (*Member, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberCreate) createSpec() (*Member, *sqlgraph.CreateSpec) {
	var (
		_node = &Member{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(member.Table, sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Permission(); ok {
		_spec.SetField(member.FieldPermission, field.TypeJSON, value)
		_node.Permission = value
	}
	if value, ok := _c.mutation.Xp(); ok {
		_spec.SetField(member.FieldXp, field.TypeUint64, value)
		_node.Xp = value
	}
	if value, ok := _c.mutation.LastXp(); ok {
		_spec.SetField(member.FieldLastXp, field.TypeTime, value)
		_node.LastXp = value
	}
	if value, ok := _c.mutation.MessageCount(); ok {
		_spec.SetField(member.FieldMessageCount, field.TypeUint64, value)
		_node.MessageCount = value
	}
	if value, ok := _c.mutation.LastNotifiedLevel(); ok {
		_spec.SetField(member.FieldLastNotifiedLevel, field.TypeUint64, value)
		_node.LastNotifiedLevel = &value
	}
	if value, ok := _c.mutation.LastMessageHashes(); ok {
		_spec.SetField(member.FieldLastMessageHashes, field.TypeJSON, value)
		_node.LastMessageHashes = value
	}
	if nodes := _c.mutation.GuildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.GuildTable,
			Columns: []string{member.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.guild_members = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.UserTable,
			Columns: []string{member.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberCreateBulk is the builder for creating many Member entities in bulk.
type MemberCreateBulk struct {
	config
	err      error
	builders []*MemberCreate
}

// Save creates the Member entities in the database.
func (_c *MemberCreateBulk) Save(ctx context.Context) ([]*Member, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Member, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberCreateBulk) SaveX(ctx context.Context) []*Member {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
