// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/disgoorg/disgo/discord"
	snowflake "github.com/disgoorg/snowflake/v2"
	"github.com/sabafly/gobot/ent/guild"
	"github.com/sabafly/gobot/ent/messagepin"
	"github.com/sabafly/gobot/ent/predicate"
	"github.com/sabafly/gobot/ent/schema"
)

// MessagePinUpdate is the builder for updating MessagePin entities.
type MessagePinUpdate struct {
	config
	hooks    []Hook
	mutation *MessagePinMutation
}

// Where appends a list predicates to the MessagePinUpdate builder.
func (_u *MessagePinUpdate) Where(ps ...predicate.MessagePin) *MessagePinUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *MessagePinUpdate) SetChannelID(v snowflake.ID) *MessagePinUpdate {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *MessagePinUpdate) SetNillableChannelID(v *snowflake.ID) *MessagePinUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *MessagePinUpdate) AddChannelID(v snowflake.ID) *MessagePinUpdate {
	_u.mutation.AddChannelID(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *MessagePinUpdate) SetContent(v string) *MessagePinUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessagePinUpdate) SetNillableContent(v *string) *MessagePinUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MessagePinUpdate) ClearContent() *MessagePinUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetEmbeds sets the "embeds" field.
func (_u *MessagePinUpdate) SetEmbeds(v []discord.Embed) *MessagePinUpdate {
	_u.mutation.SetEmbeds(v)
	return _u
}

// AppendEmbeds appends value to the "embeds" field.
func (_u *MessagePinUpdate) AppendEmbeds(v []discord.Embed) *MessagePinUpdate {
	_u.mutation.AppendEmbeds(v)
	return _u
}

// ClearEmbeds clears the value of the "embeds" field.
func (_u *MessagePinUpdate) ClearEmbeds() *MessagePinUpdate {
	_u.mutation.ClearEmbeds()
	return _u
}

// SetBeforeID sets the "before_id" field.
func (_u *MessagePinUpdate) SetBeforeID(v snowflake.ID) *MessagePinUpdate {
	_u.mutation.ResetBeforeID()
	_u.mutation.SetBeforeID(v)
	return _u
}

// SetNillableBeforeID sets the "before_id" field if the given value is not nil.
func (_u *MessagePinUpdate) SetNillableBeforeID(v *snowflake.ID) *MessagePinUpdate {
	if v != nil {
		_u.SetBeforeID(*v)
	}
	return _u
}

// AddBeforeID adds value to the "before_id" field.
func (_u *MessagePinUpdate) AddBeforeID(v snowflake.ID) *MessagePinUpdate {
	_u.mutation.AddBeforeID(v)
	return _u
}

// ClearBeforeID clears the value of the "before_id" field.
func (_u *MessagePinUpdate) ClearBeforeID() *MessagePinUpdate {
	_u.mutation.ClearBeforeID()
	return _u
}

// SetRateLimit sets the "rate_limit" field.
func (_u *MessagePinUpdate) SetRateLimit(v schema.RateLimit) *MessagePinUpdate {
	_u.mutation.SetRateLimit(v)
	return _u
}

// SetNillableRateLimit sets the "rate_limit" field if the given value is not nil.
func (_u *MessagePinUpdate) SetNillableRateLimit(v *schema.RateLimit) *MessagePinUpdate {
	if v != nil {
		_u.SetRateLimit(*v)
	}
	return _u
}

// SetGuildID sets the "guild" edge to the Guild entity by ID.
func (_u *MessagePinUpdate) SetGuildID(id snowflake.ID) *MessagePinUpdate {
	_u.mutation.SetGuildID(id)
	return _u
}

// SetGuild sets the "guild" edge to the Guild entity.
func (_u *MessagePinUpdate) SetGuild(v *Guild) *MessagePinUpdate {
	return _u.SetGuildID(v.ID)
}

// Mutation returns the MessagePinMutation object of the builder.
func (_u *MessagePinUpdate) Mutation() *MessagePinMutation {
	return _u.mutation
}

// ClearGuild clears the "guild" edge to the Guild entity.
func (_u *MessagePinUpdate) ClearGuild() *MessagePinUpdate {
	_u.mutation.ClearGuild()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessagePinUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessagePinUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessagePinUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessagePinUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessagePinUpdate) check() error {
	if _u.mutation.GuildCleared() && len(_u.mutation.GuildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessagePin.guild"`)
	}
	return nil
}

func (_u *MessagePinUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagepin.Table, messagepin.Columns, sqlgraph.NewFieldSpec(messagepin.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(messagepin.FieldChannelID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(messagepin.FieldChannelID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(messagepin.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(messagepin.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Embeds(); ok {
		_spec.SetField(messagepin.FieldEmbeds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbeds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, messagepin.FieldEmbeds, value)
		})
	}
	if _u.mutation.EmbedsCleared() {
		_spec.ClearField(messagepin.FieldEmbeds, field.TypeJSON)
	}
	if value, ok := _u.mutation.BeforeID(); ok {
		_spec.SetField(messagepin.FieldBeforeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedBeforeID(); ok {
		_spec.AddField(messagepin.FieldBeforeID, field.TypeUint64, value)
	}
	if _u.mutation.BeforeIDCleared() {
		_spec.ClearField(messagepin.FieldBeforeID, field.TypeUint64)
	}
	if value, ok := _u.mutation.RateLimit(); ok {
		_spec.SetField(messagepin.FieldRateLimit, field.TypeJSON, value)
	}
	if _u.mutation.GuildCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagepin.GuildTable,
			Columns: []string{messagepin.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GuildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagepin.GuildTable,
			Columns: []string{messagepin.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagepin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessagePinUpdateOne is the builder for updating a single MessagePin entity.
type MessagePinUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessagePinMutation
}

// SetChannelID sets the "channel_id" field.
func (_u *MessagePinUpdateOne) SetChannelID(v snowflake.ID) *MessagePinUpdateOne {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *MessagePinUpdateOne) SetNillableChannelID(v *snowflake.ID) *MessagePinUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *MessagePinUpdateOne) AddChannelID(v snowflake.ID) *MessagePinUpdateOne {
	_u.mutation.AddChannelID(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *MessagePinUpdateOne) SetContent(v string) *MessagePinUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessagePinUpdateOne) SetNillableContent(v *string) *MessagePinUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *MessagePinUpdateOne) ClearContent() *MessagePinUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetEmbeds sets the "embeds" field.
func (_u *MessagePinUpdateOne) SetEmbeds(v []discord.Embed) *MessagePinUpdateOne {
	_u.mutation.SetEmbeds(v)
	return _u
}

// AppendEmbeds appends value to the "embeds" field.
func (_u *MessagePinUpdateOne) AppendEmbeds(v []discord.Embed) *MessagePinUpdateOne {
	_u.mutation.AppendEmbeds(v)
	return _u
}

// ClearEmbeds clears the value of the "embeds" field.
func (_u *MessagePinUpdateOne) ClearEmbeds() *MessagePinUpdateOne {
	_u.mutation.ClearEmbeds()
	return _u
}

// SetBeforeID sets the "before_id" field.
func (_u *MessagePinUpdateOne) SetBeforeID(v snowflake.ID) *MessagePinUpdateOne {
	_u.mutation.ResetBeforeID()
	_u.mutation.SetBeforeID(v)
	return _u
}

// SetNillableBeforeID sets the "before_id" field if the given value is not nil.
func (_u *MessagePinUpdateOne) SetNillableBeforeID(v *snowflake.ID) *MessagePinUpdateOne {
	if v != nil {
		_u.SetBeforeID(*v)
	}
	return _u
}

// AddBeforeID adds value to the "before_id" field.
func (_u *MessagePinUpdateOne) AddBeforeID(v snowflake.ID) *MessagePinUpdateOne {
	_u.mutation.AddBeforeID(v)
	return _u
}

// ClearBeforeID clears the value of the "before_id" field.
func (_u *MessagePinUpdateOne) ClearBeforeID() *MessagePinUpdateOne {
	_u.mutation.ClearBeforeID()
	return _u
}

// SetRateLimit sets the "rate_limit" field.
func (_u *MessagePinUpdateOne) SetRateLimit(v schema.RateLimit) *MessagePinUpdateOne {
	_u.mutation.SetRateLimit(v)
	return _u
}

// SetNillableRateLimit sets the "rate_limit" field if the given value is not nil.
func (_u *MessagePinUpdateOne) SetNillableRateLimit(v *schema.RateLimit) *MessagePinUpdateOne {
	if v != nil {
		_u.SetRateLimit(*v)
	}
	return _u
}

// SetGuildID sets the "guild" edge to the Guild entity by ID.
func (_u *MessagePinUpdateOne) SetGuildID(id snowflake.ID) *MessagePinUpdateOne {
	_u.mutation.SetGuildID(id)
	return _u
}

// SetGuild sets the "guild" edge to the Guild entity.
func (_u *MessagePinUpdateOne) SetGuild(v *Guild) *MessagePinUpdateOne {
	return _u.SetGuildID(v.ID)
}

// Mutation returns the MessagePinMutation object of the builder.
func (_u *MessagePinUpdateOne) Mutation() *MessagePinMutation {
	return _u.mutation
}

// ClearGuild clears the "guild" edge to the Guild entity.
func (_u *MessagePinUpdateOne) ClearGuild() *MessagePinUpdateOne {
	_u.mutation.ClearGuild()
	return _u
}

// Where appends a list predicates to the MessagePinUpdate builder.
func (_u *MessagePinUpdateOne) Where(ps ...predicate.MessagePin) *MessagePinUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessagePinUpdateOne) Select(field string, fields ...string) *MessagePinUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MessagePin entity.
func (_u *MessagePinUpdateOne) Save(ctx context.Context) (*MessagePin, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessagePinUpdateOne) SaveX(ctx context.Context) *MessagePin {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessagePinUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessagePinUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessagePinUpdateOne) check() error {
	if _u.mutation.GuildCleared() && len(_u.mutation.GuildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MessagePin.guild"`)
	}
	return nil
}

func (_u *MessagePinUpdateOne) sqlSave(ctx context.Context) (_node *MessagePin, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(messagepin.Table, messagepin.Columns, sqlgraph.NewFieldSpec(messagepin.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessagePin.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagepin.FieldID)
		for _, f := range fields {
			if !messagepin.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messagepin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(messagepin.FieldChannelID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(messagepin.FieldChannelID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(messagepin.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(messagepin.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.Embeds(); ok {
		_spec.SetField(messagepin.FieldEmbeds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbeds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, messagepin.FieldEmbeds, value)
		})
	}
	if _u.mutation.EmbedsCleared() {
		_spec.ClearField(messagepin.FieldEmbeds, field.TypeJSON)
	}
	if value, ok := _u.mutation.BeforeID(); ok {
		_spec.SetField(messagepin.FieldBeforeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedBeforeID(); ok {
		_spec.AddField(messagepin.FieldBeforeID, field.TypeUint64, value)
	}
	if _u.mutation.BeforeIDCleared() {
		_spec.ClearField(messagepin.FieldBeforeID, field.TypeUint64)
	}
	if value, ok := _u.mutation.RateLimit(); ok {
		_spec.SetField(messagepin.FieldRateLimit, field.TypeJSON, value)
	}
	if _u.mutation.GuildCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagepin.GuildTable,
			Columns: []string{messagepin.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GuildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   messagepin.GuildTable,
			Columns: []string{messagepin.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MessagePin{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messagepin.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
