// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	snowflake "github.com/disgoorg/snowflake/v2"
	"github.com/google/uuid"
	"github.com/sabafly/gobot/ent/guild"
	"github.com/sabafly/gobot/ent/predicate"
	"github.com/sabafly/gobot/ent/rolepanel"
	"github.com/sabafly/gobot/ent/rolepaneledit"
	"github.com/sabafly/gobot/ent/rolepanelplaced"
	"github.com/sabafly/gobot/ent/schema"
)

// RolePanelUpdate is the builder for updating RolePanel entities.
type RolePanelUpdate struct {
	config
	hooks    []Hook
	mutation *RolePanelMutation
}

// Where appends a list predicates to the RolePanelUpdate builder.
func (_u *RolePanelUpdate) Where(ps ...predicate.RolePanel) *RolePanelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RolePanelUpdate) SetName(v string) *RolePanelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableName(v *string) *RolePanelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RolePanelUpdate) SetDescription(v string) *RolePanelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableDescription(v *string) *RolePanelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetRoles sets the "roles" field.
func (_u *RolePanelUpdate) SetRoles(v []schema.Role) *RolePanelUpdate {
	_u.mutation.SetRoles(v)
	return _u
}

// AppendRoles appends value to the "roles" field.
func (_u *RolePanelUpdate) AppendRoles(v []schema.Role) *RolePanelUpdate {
	_u.mutation.AppendRoles(v)
	return _u
}

// ClearRoles clears the value of the "roles" field.
func (_u *RolePanelUpdate) ClearRoles() *RolePanelUpdate {
	_u.mutation.ClearRoles()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RolePanelUpdate) SetUpdatedAt(v time.Time) *RolePanelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableUpdatedAt(v *time.Time) *RolePanelUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RolePanelUpdate) ClearUpdatedAt() *RolePanelUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetAppliedAt sets the "applied_at" field.
func (_u *RolePanelUpdate) SetAppliedAt(v time.Time) *RolePanelUpdate {
	_u.mutation.SetAppliedAt(v)
	return _u
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableAppliedAt(v *time.Time) *RolePanelUpdate {
	if v != nil {
		_u.SetAppliedAt(*v)
	}
	return _u
}

// ClearAppliedAt clears the value of the "applied_at" field.
func (_u *RolePanelUpdate) ClearAppliedAt() *RolePanelUpdate {
	_u.mutation.ClearAppliedAt()
	return _u
}

// SetGuildID sets the "guild" edge to the Guild entity by ID.
func (_u *RolePanelUpdate) SetGuildID(id snowflake.ID) *RolePanelUpdate {
	_u.mutation.SetGuildID(id)
	return _u
}

// SetGuild sets the "guild" edge to the Guild entity.
func (_u *RolePanelUpdate) SetGuild(v *Guild) *RolePanelUpdate {
	return _u.SetGuildID(v.ID)
}

// AddPlacementIDs adds the "placements" edge to the RolePanelPlaced entity by IDs.
func (_u *RolePanelUpdate) AddPlacementIDs(ids ...uuid.UUID) *RolePanelUpdate {
	_u.mutation.AddPlacementIDs(ids...)
	return _u
}

// AddPlacements adds the "placements" edges to the RolePanelPlaced entity.
func (_u *RolePanelUpdate) AddPlacements(v ...*RolePanelPlaced) *RolePanelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlacementIDs(ids...)
}

// SetEditID sets the "edit" edge to the RolePanelEdit entity by ID.
func (_u *RolePanelUpdate) SetEditID(id uuid.UUID) *RolePanelUpdate {
	_u.mutation.SetEditID(id)
	return _u
}

// SetNillableEditID sets the "edit" edge to the RolePanelEdit entity by ID if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableEditID(id *uuid.UUID) *RolePanelUpdate {
	if id != nil {
		_u = _u.SetEditID(*id)
	}
	return _u
}

// SetEdit sets the "edit" edge to the RolePanelEdit entity.
func (_u *RolePanelUpdate) SetEdit(v *RolePanelEdit) *RolePanelUpdate {
	return _u.SetEditID(v.ID)
}

// Mutation returns the RolePanelMutation object of the builder.
func (_u *RolePanelUpdate) Mutation() *RolePanelMutation {
	return _u.mutation
}

// ClearGuild clears the "guild" edge to the Guild entity.
func (_u *RolePanelUpdate) ClearGuild() *RolePanelUpdate {
	_u.mutation.ClearGuild()
	return _u
}

// ClearPlacements clears all "placements" edges to the RolePanelPlaced entity.
func (_u *RolePanelUpdate) ClearPlacements() *RolePanelUpdate {
	_u.mutation.ClearPlacements()
	return _u
}

// RemovePlacementIDs removes the "placements" edge to RolePanelPlaced entities by IDs.
func (_u *RolePanelUpdate) RemovePlacementIDs(ids ...uuid.UUID) *RolePanelUpdate {
	_u.mutation.RemovePlacementIDs(ids...)
	return _u
}

// RemovePlacements removes "placements" edges to RolePanelPlaced entities.
func (_u *RolePanelUpdate) RemovePlacements(v ...*RolePanelPlaced) *RolePanelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlacementIDs(ids...)
}

// ClearEdit clears the "edit" edge to the RolePanelEdit entity.
func (_u *RolePanelUpdate) ClearEdit() *RolePanelUpdate {
	_u.mutation.ClearEdit()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RolePanelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolePanelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RolePanelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolePanelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolePanelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rolepanel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RolePanel.name": %w`, err)}
		}
	}
	if _u.mutation.GuildCleared() && len(_u.mutation.GuildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RolePanel.guild"`)
	}
	return nil
}

func (_u *RolePanelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepanel.Table, rolepanel.Columns, sqlgraph.NewFieldSpec(rolepanel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rolepanel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rolepanel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Roles(); ok {
		_spec.SetField(rolepanel.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rolepanel.FieldRoles, value)
		})
	}
	if _u.mutation.RolesCleared() {
		_spec.ClearField(rolepanel.FieldRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepanel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(rolepanel.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AppliedAt(); ok {
		_spec.SetField(rolepanel.FieldAppliedAt, field.TypeTime, value)
	}
	if _u.mutation.AppliedAtCleared() {
		_spec.ClearField(rolepanel.FieldAppliedAt, field.TypeTime)
	}
	if _u.mutation.GuildCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepanel.GuildTable,
			Columns: []string{rolepanel.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GuildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepanel.GuildTable,
			Columns: []string{rolepanel.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlacementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rolepanel.PlacementsTable,
			Columns: []string{rolepanel.PlacementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepanelplaced.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlacementsIDs(); len(nodes) > 0 && !_u.mutation.PlacementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rolepanel.PlacementsTable,
			Columns: []string{rolepanel.PlacementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepanelplaced.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlacementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rolepanel.PlacementsTable,
			Columns: []string{rolepanel.PlacementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepanelplaced.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EditCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rolepanel.EditTable,
			Columns: []string{rolepanel.EditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepaneledit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EditIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rolepanel.EditTable,
			Columns: []string{rolepanel.EditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepaneledit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepanel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RolePanelUpdateOne is the builder for updating a single RolePanel entity.
type RolePanelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RolePanelMutation
}

// SetName sets the "name" field.
func (_u *RolePanelUpdateOne) SetName(v string) *RolePanelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableName(v *string) *RolePanelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RolePanelUpdateOne) SetDescription(v string) *RolePanelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableDescription(v *string) *RolePanelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetRoles sets the "roles" field.
func (_u *RolePanelUpdateOne) SetRoles(v []schema.Role) *RolePanelUpdateOne {
	_u.mutation.SetRoles(v)
	return _u
}

// AppendRoles appends value to the "roles" field.
func (_u *RolePanelUpdateOne) AppendRoles(v []schema.Role) *RolePanelUpdateOne {
	_u.mutation.AppendRoles(v)
	return _u
}

// ClearRoles clears the value of the "roles" field.
func (_u *RolePanelUpdateOne) ClearRoles() *RolePanelUpdateOne {
	_u.mutation.ClearRoles()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RolePanelUpdateOne) SetUpdatedAt(v time.Time) *RolePanelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableUpdatedAt(v *time.Time) *RolePanelUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *RolePanelUpdateOne) ClearUpdatedAt() *RolePanelUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetAppliedAt sets the "applied_at" field.
func (_u *RolePanelUpdateOne) SetAppliedAt(v time.Time) *RolePanelUpdateOne {
	_u.mutation.SetAppliedAt(v)
	return _u
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableAppliedAt(v *time.Time) *RolePanelUpdateOne {
	if v != nil {
		_u.SetAppliedAt(*v)
	}
	return _u
}

// ClearAppliedAt clears the value of the "applied_at" field.
func (_u *RolePanelUpdateOne) ClearAppliedAt() *RolePanelUpdateOne {
	_u.mutation.ClearAppliedAt()
	return _u
}

// SetGuildID sets the "guild" edge to the Guild entity by ID.
func (_u *RolePanelUpdateOne) SetGuildID(id snowflake.ID) *RolePanelUpdateOne {
	_u.mutation.SetGuildID(id)
	return _u
}

// SetGuild sets the "guild" edge to the Guild entity.
func (_u *RolePanelUpdateOne) SetGuild(v *Guild) *RolePanelUpdateOne {
	return _u.SetGuildID(v.ID)
}

// AddPlacementIDs adds the "placements" edge to the RolePanelPlaced entity by IDs.
func (_u *RolePanelUpdateOne) AddPlacementIDs(ids ...uuid.UUID) *RolePanelUpdateOne {
	_u.mutation.AddPlacementIDs(ids...)
	return _u
}

// AddPlacements adds the "placements" edges to the RolePanelPlaced entity.
func (_u *RolePanelUpdateOne) AddPlacements(v ...*RolePanelPlaced) *RolePanelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlacementIDs(ids...)
}

// SetEditID sets the "edit" edge to the RolePanelEdit entity by ID.
func (_u *RolePanelUpdateOne) SetEditID(id uuid.UUID) *RolePanelUpdateOne {
	_u.mutation.SetEditID(id)
	return _u
}

// SetNillableEditID sets the "edit" edge to the RolePanelEdit entity by ID if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableEditID(id *uuid.UUID) *RolePanelUpdateOne {
	if id != nil {
		_u = _u.SetEditID(*id)
	}
	return _u
}

// SetEdit sets the "edit" edge to the RolePanelEdit entity.
func (_u *RolePanelUpdateOne) SetEdit(v *RolePanelEdit) *RolePanelUpdateOne {
	return _u.SetEditID(v.ID)
}

// Mutation returns the RolePanelMutation object of the builder.
func (_u *RolePanelUpdateOne) Mutation() *RolePanelMutation {
	return _u.mutation
}

// ClearGuild clears the "guild" edge to the Guild entity.
func (_u *RolePanelUpdateOne) ClearGuild() *RolePanelUpdateOne {
	_u.mutation.ClearGuild()
	return _u
}

// ClearPlacements clears all "placements" edges to the RolePanelPlaced entity.
func (_u *RolePanelUpdateOne) ClearPlacements() *RolePanelUpdateOne {
	_u.mutation.ClearPlacements()
	return _u
}

// RemovePlacementIDs removes the "placements" edge to RolePanelPlaced entities by IDs.
func (_u *RolePanelUpdateOne) RemovePlacementIDs(ids ...uuid.UUID) *RolePanelUpdateOne {
	_u.mutation.RemovePlacementIDs(ids...)
	return _u
}

// RemovePlacements removes "placements" edges to RolePanelPlaced entities.
func (_u *RolePanelUpdateOne) RemovePlacements(v ...*RolePanelPlaced) *RolePanelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlacementIDs(ids...)
}

// ClearEdit clears the "edit" edge to the RolePanelEdit entity.
func (_u *RolePanelUpdateOne) ClearEdit() *RolePanelUpdateOne {
	_u.mutation.ClearEdit()
	return _u
}

// Where appends a list predicates to the RolePanelUpdate builder.
func (_u *RolePanelUpdateOne) Where(ps ...predicate.RolePanel) *RolePanelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RolePanelUpdateOne) Select(field string, fields ...string) *RolePanelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RolePanel entity.
func (_u *RolePanelUpdateOne) Save(ctx context.Context) (*RolePanel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolePanelUpdateOne) SaveX(ctx context.Context) *RolePanel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RolePanelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolePanelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolePanelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rolepanel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RolePanel.name": %w`, err)}
		}
	}
	if _u.mutation.GuildCleared() && len(_u.mutation.GuildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RolePanel.guild"`)
	}
	return nil
}

func (_u *RolePanelUpdateOne) sqlSave(ctx context.Context) (_node *RolePanel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepanel.Table, rolepanel.Columns, sqlgraph.NewFieldSpec(rolepanel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RolePanel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rolepanel.FieldID)
		for _, f := range fields {
			if !rolepanel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rolepanel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rolepanel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rolepanel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Roles(); ok {
		_spec.SetField(rolepanel.FieldRoles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRoles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rolepanel.FieldRoles, value)
		})
	}
	if _u.mutation.RolesCleared() {
		_spec.ClearField(rolepanel.FieldRoles, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepanel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(rolepanel.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AppliedAt(); ok {
		_spec.SetField(rolepanel.FieldAppliedAt, field.TypeTime, value)
	}
	if _u.mutation.AppliedAtCleared() {
		_spec.ClearField(rolepanel.FieldAppliedAt, field.TypeTime)
	}
	if _u.mutation.GuildCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepanel.GuildTable,
			Columns: []string{rolepanel.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GuildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepanel.GuildTable,
			Columns: []string{rolepanel.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlacementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rolepanel.PlacementsTable,
			Columns: []string{rolepanel.PlacementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepanelplaced.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlacementsIDs(); len(nodes) > 0 && !_u.mutation.PlacementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rolepanel.PlacementsTable,
			Columns: []string{rolepanel.PlacementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepanelplaced.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlacementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rolepanel.PlacementsTable,
			Columns: []string{rolepanel.PlacementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepanelplaced.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EditCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rolepanel.EditTable,
			Columns: []string{rolepanel.EditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepaneledit.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EditIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rolepanel.EditTable,
			Columns: []string{rolepanel.EditColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepaneledit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RolePanel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepanel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
