// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sabafly/gobot/ent/predicate"
	"github.com/sabafly/gobot/ent/thread1000channel"
)

// Thread1000ChannelDelete is the builder for deleting a Thread1000Channel entity.
type Thread1000ChannelDelete struct {
	config
	hooks    []Hook
	mutation *Thread1000ChannelMutation
}

// Where appends a list predicates to the Thread1000ChannelDelete builder.
func (td *Thread1000ChannelDelete) Where(ps ...predicate.Thread1000Channel) *Thread1000ChannelDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *Thread1000ChannelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *Thread1000ChannelDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *Thread1000ChannelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(thread1000channel.Table, sqlgraph.NewFieldSpec(thread1000channel.FieldID, field.TypeUUID))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// Thread1000ChannelDeleteOne is the builder for deleting a single Thread1000Channel entity.
type Thread1000ChannelDeleteOne struct {
	td *Thread1000ChannelDelete
}

// Where appends a list predicates to the Thread1000ChannelDelete builder.
func (tdo *Thread1000ChannelDeleteOne) Where(ps ...predicate.Thread1000Channel) *Thread1000ChannelDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *Thread1000ChannelDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{thread1000channel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *Thread1000ChannelDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
