// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	snowflake "github.com/disgoorg/snowflake/v2"
	"github.com/google/uuid"
	"github.com/sabafly/gobot/ent/guild"
	"github.com/sabafly/gobot/ent/predicate"
	"github.com/sabafly/gobot/ent/thread1000"
	"github.com/sabafly/gobot/ent/thread1000channel"
)

// Thread1000ChannelUpdate is the builder for updating Thread1000Channel entities.
type Thread1000ChannelUpdate struct {
	config
	hooks    []Hook
	mutation *Thread1000ChannelMutation
}

// Where appends a list predicates to the Thread1000ChannelUpdate builder.
func (_u *Thread1000ChannelUpdate) Where(ps ...predicate.Thread1000Channel) *Thread1000ChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *Thread1000ChannelUpdate) SetName(v string) *Thread1000ChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *Thread1000ChannelUpdate) SetNillableName(v *string) *Thread1000ChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *Thread1000ChannelUpdate) ClearName() *Thread1000ChannelUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetAnonymousName sets the "anonymous_name" field.
func (_u *Thread1000ChannelUpdate) SetAnonymousName(v string) *Thread1000ChannelUpdate {
	_u.mutation.SetAnonymousName(v)
	return _u
}

// SetNillableAnonymousName sets the "anonymous_name" field if the given value is not nil.
func (_u *Thread1000ChannelUpdate) SetNillableAnonymousName(v *string) *Thread1000ChannelUpdate {
	if v != nil {
		_u.SetAnonymousName(*v)
	}
	return _u
}

// ClearAnonymousName clears the value of the "anonymous_name" field.
func (_u *Thread1000ChannelUpdate) ClearAnonymousName() *Thread1000ChannelUpdate {
	_u.mutation.ClearAnonymousName()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *Thread1000ChannelUpdate) SetChannelID(v snowflake.ID) *Thread1000ChannelUpdate {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *Thread1000ChannelUpdate) SetNillableChannelID(v *snowflake.ID) *Thread1000ChannelUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *Thread1000ChannelUpdate) AddChannelID(v snowflake.ID) *Thread1000ChannelUpdate {
	_u.mutation.AddChannelID(v)
	return _u
}

// SetGuildID sets the "guild" edge to the Guild entity by ID.
func (_u *Thread1000ChannelUpdate) SetGuildID(id snowflake.ID) *Thread1000ChannelUpdate {
	_u.mutation.SetGuildID(id)
	return _u
}

// SetGuild sets the "guild" edge to the Guild entity.
func (_u *Thread1000ChannelUpdate) SetGuild(v *Guild) *Thread1000ChannelUpdate {
	return _u.SetGuildID(v.ID)
}

// AddThreadIDs adds the "threads" edge to the Thread1000 entity by IDs.
func (_u *Thread1000ChannelUpdate) AddThreadIDs(ids ...uuid.UUID) *Thread1000ChannelUpdate {
	_u.mutation.AddThreadIDs(ids...)
	return _u
}

// AddThreads adds the "threads" edges to the Thread1000 entity.
func (_u *Thread1000ChannelUpdate) AddThreads(v ...*Thread1000) *Thread1000ChannelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThreadIDs(ids...)
}

// Mutation returns the Thread1000ChannelMutation object of the builder.
func (_u *Thread1000ChannelUpdate) Mutation() *Thread1000ChannelMutation {
	return _u.mutation
}

// ClearGuild clears the "guild" edge to the Guild entity.
func (_u *Thread1000ChannelUpdate) ClearGuild() *Thread1000ChannelUpdate {
	_u.mutation.ClearGuild()
	return _u
}

// ClearThreads clears all "threads" edges to the Thread1000 entity.
func (_u *Thread1000ChannelUpdate) ClearThreads() *Thread1000ChannelUpdate {
	_u.mutation.ClearThreads()
	return _u
}

// RemoveThreadIDs removes the "threads" edge to Thread1000 entities by IDs.
func (_u *Thread1000ChannelUpdate) RemoveThreadIDs(ids ...uuid.UUID) *Thread1000ChannelUpdate {
	_u.mutation.RemoveThreadIDs(ids...)
	return _u
}

// RemoveThreads removes "threads" edges to Thread1000 entities.
func (_u *Thread1000ChannelUpdate) RemoveThreads(v ...*Thread1000) *Thread1000ChannelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThreadIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Thread1000ChannelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Thread1000ChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Thread1000ChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Thread1000ChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Thread1000ChannelUpdate) check() error {
	if _u.mutation.GuildCleared() && len(_u.mutation.GuildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Thread1000Channel.guild"`)
	}
	return nil
}

func (_u *Thread1000ChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(thread1000channel.Table, thread1000channel.Columns, sqlgraph.NewFieldSpec(thread1000channel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(thread1000channel.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(thread1000channel.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AnonymousName(); ok {
		_spec.SetField(thread1000channel.FieldAnonymousName, field.TypeString, value)
	}
	if _u.mutation.AnonymousNameCleared() {
		_spec.ClearField(thread1000channel.FieldAnonymousName, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(thread1000channel.FieldChannelID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(thread1000channel.FieldChannelID, field.TypeUint64, value)
	}
	if _u.mutation.GuildCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread1000channel.GuildTable,
			Columns: []string{thread1000channel.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GuildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread1000channel.GuildTable,
			Columns: []string{thread1000channel.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThreadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread1000channel.ThreadsTable,
			Columns: []string{thread1000channel.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread1000.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThreadsIDs(); len(nodes) > 0 && !_u.mutation.ThreadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread1000channel.ThreadsTable,
			Columns: []string{thread1000channel.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread1000.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread1000channel.ThreadsTable,
			Columns: []string{thread1000channel.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread1000.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thread1000channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Thread1000ChannelUpdateOne is the builder for updating a single Thread1000Channel entity.
type Thread1000ChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Thread1000ChannelMutation
}

// SetName sets the "name" field.
func (_u *Thread1000ChannelUpdateOne) SetName(v string) *Thread1000ChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *Thread1000ChannelUpdateOne) SetNillableName(v *string) *Thread1000ChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *Thread1000ChannelUpdateOne) ClearName() *Thread1000ChannelUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetAnonymousName sets the "anonymous_name" field.
func (_u *Thread1000ChannelUpdateOne) SetAnonymousName(v string) *Thread1000ChannelUpdateOne {
	_u.mutation.SetAnonymousName(v)
	return _u
}

// SetNillableAnonymousName sets the "anonymous_name" field if the given value is not nil.
func (_u *Thread1000ChannelUpdateOne) SetNillableAnonymousName(v *string) *Thread1000ChannelUpdateOne {
	if v != nil {
		_u.SetAnonymousName(*v)
	}
	return _u
}

// ClearAnonymousName clears the value of the "anonymous_name" field.
func (_u *Thread1000ChannelUpdateOne) ClearAnonymousName() *Thread1000ChannelUpdateOne {
	_u.mutation.ClearAnonymousName()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *Thread1000ChannelUpdateOne) SetChannelID(v snowflake.ID) *Thread1000ChannelUpdateOne {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *Thread1000ChannelUpdateOne) SetNillableChannelID(v *snowflake.ID) *Thread1000ChannelUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *Thread1000ChannelUpdateOne) AddChannelID(v snowflake.ID) *Thread1000ChannelUpdateOne {
	_u.mutation.AddChannelID(v)
	return _u
}

// SetGuildID sets the "guild" edge to the Guild entity by ID.
func (_u *Thread1000ChannelUpdateOne) SetGuildID(id snowflake.ID) *Thread1000ChannelUpdateOne {
	_u.mutation.SetGuildID(id)
	return _u
}

// SetGuild sets the "guild" edge to the Guild entity.
func (_u *Thread1000ChannelUpdateOne) SetGuild(v *Guild) *Thread1000ChannelUpdateOne {
	return _u.SetGuildID(v.ID)
}

// AddThreadIDs adds the "threads" edge to the Thread1000 entity by IDs.
func (_u *Thread1000ChannelUpdateOne) AddThreadIDs(ids ...uuid.UUID) *Thread1000ChannelUpdateOne {
	_u.mutation.AddThreadIDs(ids...)
	return _u
}

// AddThreads adds the "threads" edges to the Thread1000 entity.
func (_u *Thread1000ChannelUpdateOne) AddThreads(v ...*Thread1000) *Thread1000ChannelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThreadIDs(ids...)
}

// Mutation returns the Thread1000ChannelMutation object of the builder.
func (_u *Thread1000ChannelUpdateOne) Mutation() *Thread1000ChannelMutation {
	return _u.mutation
}

// ClearGuild clears the "guild" edge to the Guild entity.
func (_u *Thread1000ChannelUpdateOne) ClearGuild() *Thread1000ChannelUpdateOne {
	_u.mutation.ClearGuild()
	return _u
}

// ClearThreads clears all "threads" edges to the Thread1000 entity.
func (_u *Thread1000ChannelUpdateOne) ClearThreads() *Thread1000ChannelUpdateOne {
	_u.mutation.ClearThreads()
	return _u
}

// RemoveThreadIDs removes the "threads" edge to Thread1000 entities by IDs.
func (_u *Thread1000ChannelUpdateOne) RemoveThreadIDs(ids ...uuid.UUID) *Thread1000ChannelUpdateOne {
	_u.mutation.RemoveThreadIDs(ids...)
	return _u
}

// RemoveThreads removes "threads" edges to Thread1000 entities.
func (_u *Thread1000ChannelUpdateOne) RemoveThreads(v ...*Thread1000) *Thread1000ChannelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThreadIDs(ids...)
}

// Where appends a list predicates to the Thread1000ChannelUpdate builder.
func (_u *Thread1000ChannelUpdateOne) Where(ps ...predicate.Thread1000Channel) *Thread1000ChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Thread1000ChannelUpdateOne) Select(field string, fields ...string) *Thread1000ChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Thread1000Channel entity.
func (_u *Thread1000ChannelUpdateOne) Save(ctx context.Context) (*Thread1000Channel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Thread1000ChannelUpdateOne) SaveX(ctx context.Context) *Thread1000Channel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Thread1000ChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Thread1000ChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Thread1000ChannelUpdateOne) check() error {
	if _u.mutation.GuildCleared() && len(_u.mutation.GuildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Thread1000Channel.guild"`)
	}
	return nil
}

func (_u *Thread1000ChannelUpdateOne) sqlSave(ctx context.Context) (_node *Thread1000Channel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(thread1000channel.Table, thread1000channel.Columns, sqlgraph.NewFieldSpec(thread1000channel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Thread1000Channel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, thread1000channel.FieldID)
		for _, f := range fields {
			if !thread1000channel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != thread1000channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(thread1000channel.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(thread1000channel.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.AnonymousName(); ok {
		_spec.SetField(thread1000channel.FieldAnonymousName, field.TypeString, value)
	}
	if _u.mutation.AnonymousNameCleared() {
		_spec.ClearField(thread1000channel.FieldAnonymousName, field.TypeString)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(thread1000channel.FieldChannelID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(thread1000channel.FieldChannelID, field.TypeUint64, value)
	}
	if _u.mutation.GuildCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread1000channel.GuildTable,
			Columns: []string{thread1000channel.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GuildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread1000channel.GuildTable,
			Columns: []string{thread1000channel.GuildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(guild.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThreadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread1000channel.ThreadsTable,
			Columns: []string{thread1000channel.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread1000.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThreadsIDs(); len(nodes) > 0 && !_u.mutation.ThreadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread1000channel.ThreadsTable,
			Columns: []string{thread1000channel.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread1000.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThreadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread1000channel.ThreadsTable,
			Columns: []string{thread1000channel.ThreadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread1000.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Thread1000Channel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thread1000channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
